version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/thunder-web"
    schedule:
      interval: "weekly"
    groups:
      frontend-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      root-tooling:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"
    open-pull-requests-limit: 5
