version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/thunder-web'
    schedule:
      interval: 'weekly'
    groups:
      frontend-dependencies:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
    open-pull-requests-limit: 5

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      root-tooling:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
    open-pull-requests-limit: 5

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      actions:
        patterns:
          - '*'
    open-pull-requests-limit: 5
